### ISSUE TITLE
🔄 Death on relog

### ISSUE THREAD

**Issue by EOussama** [dayz-survival/board#12]
Some players die as soon as they log in.

**Comment by EOussama** [comment]
Needs more investigating

**Comment by eoussama** [comment]
Fixed by  #37

**Comment by eoussama** [comment]
The problem persists, refer to the player's `spawned` state not assigned upon logging in.

**Comment by eoussama** [comment]
![Image](https://user-images.githubusercontent.com/22644543/180797991-856aadf1-9787-4f8d-9bfb-5318e1e51efb.png)

Account susan has the same issue, the interesting part is that even when she's offline, her stats are kept on the server's memory, as though her stats never reset. This might be related to the problem.

**Comment by eoussama** [comment]
Looks like the issue was caused by modded files of the game.
