### ISSUE TITLE
🏗 Base building

### ISSUE THREAD

**Issue by EOussama** [dayz-survival/board#14]
![Image](https://user-images.githubusercontent.com/22644543/179546158-f6b34f3d-97ab-47f4-a260-1fd10bbf968b.png)

**Comment by eoussama** [comment]
Display pictures of structures on the crafting table.
Adding pictures on walls, fences, furniture, etc. It is hard to find the right wall to make on your base since there is no picture of it displayed on the crafting table.

**Comment by eoussama** [comment]
The preview dialog used can't show SA-MP models.
