### ISSUE TITLE
〽 New commands and Tweaks.

### ISSUE THREAD

**Issue by TheOneAkashi** [dayz-survival/board#2]
**Feature description:**
New commands: /giveachivement, /itemlist.
New tweaks: Add the hunger, thirst, karma, blood and heat to the /setstats command. And add the crafting table to /giveitem command.
**How do you think this feature will benefit the overall experience:**
Gives the management team more free space to act. And more opportunities
**Additional context**
None.

**Comment by EOussama** [comment]
Moved to development board.

**Comment by eoussama** [comment]
Treated by #55
