### ISSUE TITLE
🏍 Bikes fix bug

### ISSUE THREAD

**Issue by TheOneAkashi** [dayz-survival/board#3]
**Describe the bug**
The range of where you can fix bikes is broken, look how far it is.
**To Reproduce**
1. Go near a bike, a bit far ahead
3. Press LALT
4. Problem happens...

**Expected behavior**
You will get the fix dialog pop up even tho you're far from the bike
**Screenshots**
![image](https://user-images.githubusercontent.com/109487273/179515394-c0544681-4810-4b28-a126-f1eaffc87a01.png)
![image](https://user-images.githubusercontent.com/109487273/179515449-0898ab67-adf2-4cd8-bed4-52e421e98881.png)

**Additional context**
This bug might happen to all vehicles and not just bikes.

**Comment by EOussama** [comment]
Moved to development board.
